services:
  app:
    build:
      target: builder
    command: pnpm dev --host --port 3000
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./package.json:/app/package.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./svelte.config.js:/app/svelte.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
